In [11]:
import numpy as np
import pandas as pd
import random

In [2]:
dati = pd.read_csv("Dataset/Reviews_With_Metadata.csv", low_memory=False)
print(dati.shape)

(1773588, 13)

In [19]:
# rimuovere eventuali elementi NULL in product_title e product_brand
dati = dati.dropna(subset=["product_title","product_brand","review_upvote"])
dati.head()

,product_asin,reviewer_id,reviewer_name,review_score,review_time,review_time_unix,review_summary,review_upvote,review_text,product_title,product_brand,Review_ID
10,0176496920,A3CQXY7BIMJEAK,Amazon Customer,1,2017-01-22 00:00:00,1485043200,"Product ok, business models s**ks",2,"The product is ok. Works fine, with enough fun...",Turning Technologies Response Card (RCRF-03),"Turning Technologies, LLC",Pair_A3CQXY7BIMJEAK-0176496920
12,0176496920,A10LKHY0O6OBLB,Joseph Doye,2,2017-01-10 00:00:00,1484006400,Make sure you don't need a license for the sof...,5,I bought one of these used for my course. Seem...,Turning Technologies Response Card (RCRF-03),"Turning Technologies, LLC",Pair_A10LKHY0O6OBLB-0176496920
23,0176496920,ADFGHSXYA6CAI,Amazon Customer,3,2016-09-06 00:00:00,1473120000,"Works well, but stick with the app if you can",9,"The device came fully charged, I would recomme...",Turning Technologies Response Card (RCRF-03),"Turning Technologies, LLC",Pair_ADFGHSXYA6CAI-0176496920
27,0176496920,A244VCNZM968SE,Betty Rain,5,2016-03-06 00:00:00,1457222400,Reliable,3,This worked perfectly in every lecture that I ...,Turning Technologies Response Card (RCRF-03),"Turning Technologies, LLC",Pair_A244VCNZM968SE-0176496920
29,0176496920,A2DE2X4ZHTLAEW,Benson Boy,1,2016-01-24 00:00:00,1453593600,just say no,2,"don't worry it works, if you buy a subscriptio...",Turning Technologies Response Card (RCRF-03),"Turning Technologies, LLC",Pair_A2DE2X4ZHTLAEW-0176496920

In [20]:
dati.to_csv("Dataset/Reviews_With_Metadata.csv", index=False)

In [6]:
# aggiungere la colonna id_univoco per ogni recensione
# Pair_{reviewer_id}-{product_asin}
arr = ["Pair_"+dati.iloc[i]['reviewer_id']+"-"+dati.iloc[i]['product_asin'] for i in range(dati.shape[0])]
print(arr[0])
dati['Review_ID'] = arr

Pair_A3FANY5GOT5X0W-0176496920

In [8]:
dati.to_csv("Dataset/Reviews_With_Metadata.csv", index=False)
print("done")

done

In [27]:
hits_df = pd.DataFrame(columns=["Posizione_1","Posizione_2","Posizione_3","Posizione_4","Posizione_5"])
print(hits_df)

Empty DataFrame
Columns: [Posizione_1, Posizione_2, Posizione_3, Posizione_4, Posizione_5]
Index: []

In [ ]:
# creare la tabella delle HIT con 15 righe e 5 colonne
# 1 colonna estrarre a caso un array di 15 righe del DF dati
# 2 colonna array shiftato a DX di 1
# 3 colonna array shiftato a DX di 2
# ...

In [29]:
random_rews = list(np.random.choice(dati['Review_ID'], size=15, replace=False))
print(random_rews)

['Pair_A1EOXQ11EA3UCO-B000SXK25M', 'Pair_A2BVGGZDYZ6D5R-B01DF31DQS', 'Pair_A1V64OGQQZBWRR-B00AZAMQZM', 'Pair_A2RBZ3MKKAT1EI-B009WTNMXM', 'Pair_A10HBBTCNPE2EE-B0002YTLFE', 'Pair_A3I89XKVHNI3XZ-B00802O0EM', 'Pair_A1371U3O5GLDYM-B005IBNWEW', 'Pair_A1M261XG44L4ZT-B016HL5MRG', 'Pair_A3HJ2JUP75IP8Z-B01GSSJDTQ', 'Pair_A2OHYT8G4SDQFW-B00HHEND2Y', 'Pair_A2ZMA7TAZJU0SB-B004X2HXPQ', 'Pair_A2A3FT8HF1NYKC-B001O4LK14', 'Pair_A3PMZAT1NF4OKY-B00WSUK12M', 'Pair_A18WESE1YDVVD-B00094GPQK', 'Pair_A28KZH2Q680PLM-B00XX8XPCQ']

In [30]:
hits_df['Posizione_1'] = random_rews
for i in range(2,6):
    col_name = "Posizione_"+str(i)
    random_rews = random_rews[-1:] + random_rews[:-1]
    hits_df[col_name] = random_rews
hits_df.head()

,Posizione_1,Posizione_2,Posizione_3,Posizione_4,Posizione_5
0,Pair_A1EOXQ11EA3UCO-B000SXK25M,Pair_A28KZH2Q680PLM-B00XX8XPCQ,Pair_A18WESE1YDVVD-B00094GPQK,Pair_A3PMZAT1NF4OKY-B00WSUK12M,Pair_A2A3FT8HF1NYKC-B001O4LK14
1,Pair_A2BVGGZDYZ6D5R-B01DF31DQS,Pair_A1EOXQ11EA3UCO-B000SXK25M,Pair_A28KZH2Q680PLM-B00XX8XPCQ,Pair_A18WESE1YDVVD-B00094GPQK,Pair_A3PMZAT1NF4OKY-B00WSUK12M
2,Pair_A1V64OGQQZBWRR-B00AZAMQZM,Pair_A2BVGGZDYZ6D5R-B01DF31DQS,Pair_A1EOXQ11EA3UCO-B000SXK25M,Pair_A28KZH2Q680PLM-B00XX8XPCQ,Pair_A18WESE1YDVVD-B00094GPQK
3,Pair_A2RBZ3MKKAT1EI-B009WTNMXM,Pair_A1V64OGQQZBWRR-B00AZAMQZM,Pair_A2BVGGZDYZ6D5R-B01DF31DQS,Pair_A1EOXQ11EA3UCO-B000SXK25M,Pair_A28KZH2Q680PLM-B00XX8XPCQ
4,Pair_A10HBBTCNPE2EE-B0002YTLFE,Pair_A2RBZ3MKKAT1EI-B009WTNMXM,Pair_A1V64OGQQZBWRR-B00AZAMQZM,Pair_A2BVGGZDYZ6D5R-B01DF31DQS,Pair_A1EOXQ11EA3UCO-B000SXK25M

In [31]:
hits_df.to_csv("Dataset/hits_df.csv",index=False)